// ParticleFlowVK.cpp — Vulkan NDK Renderer
// NEXUS Engineering — Canyon (Kaneon)
//
// SPIR-V is embedded at compile time via xxd-generated headers produced by
// CMakeLists.txt:  glslc shader → .spv → xxd -i → .spv.h (uint8_t array)
// We reinterpret the byte array as uint32_t* for vkCreateShaderModule.

#include "ParticleFlowVK.h"

#include <android/log.h>
#include <android/native_window.h>
#include <vulkan/vulkan_android.h>

#include <cstring>
#include <cmath>
#include <cassert>
#include <algorithm>

// Embedded SPIR-V headers (generated by CMakeLists.txt compile_shader commands)
#include "init.comp.spv.h"
#include "update.comp.spv.h"
#include "particles.vert.spv.h"
#include "particles.frag.spv.h"

#define LOG_TAG "ParticleFlowVK"
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO,  LOG_TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)

#define VK_CHECK(expr) do { \
    VkResult _r = (expr); \
    if (_r != VK_SUCCESS) { \
        LOGE(#expr " failed: %d", (int)_r); \
        return false; \
    } \
} while(0)

// ── Public: init ─────────────────────────────────────────────────────────────

bool ParticleFlowVK::init(ANativeWindow* window, int width, int height) {
    cpc_.numParticles = 50000;
    cpc_.numTouch     = 5;
    cpc_.attract      = 100.f;
    cpc_.drag         = 0.96f;
    cpc_.width        = (float)width;
    cpc_.height       = (float)height;
    cpc_.slowH = 0.67f; cpc_.slowS = 1.f; cpc_.slowV = 1.f;
    cpc_.fastH = 0.0f;  cpc_.fastS = 1.f; cpc_.fastV = 1.f;
    cpc_.hueDir    = 0;
    cpc_.frameSeed = 0;

    gpc_.width     = (float)width;
    gpc_.height    = (float)height;
    gpc_.pointSize = 4.f;

    if (!createInstance())         return false;
    if (!selectPhysicalDevice())   return false;
    if (!createDevice())           return false;
    if (!createSurface(window))    return false;
    if (!createSwapchain(width, height)) return false;
    if (!createRenderPass())       return false;
    if (!createFramebuffers())     return false;
    if (!createBuffers())          return false;
    if (!createDescriptors())      return false;
    if (!createComputePipelines()) return false;
    if (!createGraphicsPipeline()) return false;
    if (!createCommandResources()) return false;
    if (!createSyncObjects())      return false;

    initialized_ = true;
    resetParticles();
    LOGI("init complete (%dx%d, %d particles)", width, height, cpc_.numParticles);
    return true;
}

void ParticleFlowVK::resize(int width, int height) {
    if (!initialized_) return;
    cpc_.width  = gpc_.width  = (float)width;
    cpc_.height = gpc_.height = (float)height;
    recreateSwapchain(width, height);
}

void ParticleFlowVK::destroy() {
    if (!initialized_) return;
    vkDeviceWaitIdle(device_);

    vkDestroyFence(device_, frameFence_, nullptr);
    vkDestroySemaphore(device_, renderDoneSem_, nullptr);
    vkDestroySemaphore(device_, imgAvailSem_, nullptr);
    vkFreeCommandBuffers(device_, cmdPool_, 1, &cmdBuf_);
    vkDestroyCommandPool(device_, cmdPool_, nullptr);

    vkDestroyPipeline(device_, graphicsPipeline_, nullptr);
    vkDestroyPipelineLayout(device_, graphicsLayout_, nullptr);
    vkDestroyPipeline(device_, updatePipeline_, nullptr);
    vkDestroyPipeline(device_, initPipeline_, nullptr);
    vkDestroyPipelineLayout(device_, computeLayout_, nullptr);

    vkFreeDescriptorSets(device_, descPool_, 1, &descSet_);
    vkDestroyDescriptorPool(device_, descPool_, nullptr);
    vkDestroyDescriptorSetLayout(device_, descSetLayout_, nullptr);

    vkUnmapMemory(device_, touchMem_);
    vkDestroyBuffer(device_, touchBuf_, nullptr); vkFreeMemory(device_, touchMem_, nullptr);
    vkDestroyBuffer(device_, colBuf_,   nullptr); vkFreeMemory(device_, colMem_,   nullptr);
    vkDestroyBuffer(device_, velBuf_,   nullptr); vkFreeMemory(device_, velMem_,   nullptr);
    vkDestroyBuffer(device_, posBuf_,   nullptr); vkFreeMemory(device_, posMem_,   nullptr);

    destroySwapchain();
    vkDestroyRenderPass(device_, renderPass_, nullptr);
    vkDestroySurfaceKHR(instance_, surface_, nullptr);
    vkDestroyDevice(device_, nullptr);
    vkDestroyInstance(instance_, nullptr);
    initialized_ = false;
}

// ── Public: drawFrame ────────────────────────────────────────────────────────

void ParticleFlowVK::drawFrame() {
    if (!initialized_) return;

    // 1. Wait for previous frame
    vkWaitForFences(device_, 1, &frameFence_, VK_TRUE, UINT64_MAX);
    vkResetFences(device_, 1, &frameFence_);

    // 2. Acquire swapchain image
    uint32_t imageIndex = 0;
    VkResult result = vkAcquireNextImageKHR(device_, swapchain_, UINT64_MAX,
                                             imgAvailSem_, VK_NULL_HANDLE, &imageIndex);
    if (result == VK_ERROR_OUT_OF_DATE_KHR) {
        recreateSwapchain((int)cpc_.width, (int)cpc_.height);
        return;
    }

    // 3. Record command buffer
    vkResetCommandBuffer(cmdBuf_, 0);

    VkCommandBufferBeginInfo beginInfo{VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};
    beginInfo.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
    vkBeginCommandBuffer(cmdBuf_, &beginInfo);

    // 4a. Barrier: host writes to touch buffer → compute shader reads
    // HOST_COHERENT means no flush needed, but we still need an execution barrier
    // so the GPU sees the CPU-written touch data before the compute dispatch.
    {
        VkMemoryBarrier hostBarrier{VK_STRUCTURE_TYPE_MEMORY_BARRIER};
        hostBarrier.srcAccessMask = VK_ACCESS_HOST_WRITE_BIT;
        hostBarrier.dstAccessMask = VK_ACCESS_SHADER_READ_BIT;
        vkCmdPipelineBarrier(cmdBuf_,
            VK_PIPELINE_STAGE_HOST_BIT,
            VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
            0, 1, &hostBarrier, 0, nullptr, 0, nullptr);
    }

    // 4b. Compute: update particles
    vkCmdBindPipeline(cmdBuf_, VK_PIPELINE_BIND_POINT_COMPUTE, updatePipeline_);
    vkCmdBindDescriptorSets(cmdBuf_, VK_PIPELINE_BIND_POINT_COMPUTE,
                             computeLayout_, 0, 1, &descSet_, 0, nullptr);
    cpc_.frameSeed++;
    vkCmdPushConstants(cmdBuf_, computeLayout_, VK_SHADER_STAGE_COMPUTE_BIT,
                        0, sizeof(ComputePC), &cpc_);
    uint32_t groups = (cpc_.numParticles + 255) / 256;
    vkCmdDispatch(cmdBuf_, groups, 1, 1);

    // 5. Barrier: compute write → vertex read (pos + col buffers)
    VkBufferMemoryBarrier barriers[2] = {};
    barriers[0].sType               = VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER;
    barriers[0].srcAccessMask       = VK_ACCESS_SHADER_WRITE_BIT;
    barriers[0].dstAccessMask       = VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT;
    barriers[0].srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
    barriers[0].dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
    barriers[0].buffer              = posBuf_;
    barriers[0].offset              = 0;
    barriers[0].size                = VK_WHOLE_SIZE;

    barriers[1] = barriers[0];
    barriers[1].buffer = colBuf_;

    vkCmdPipelineBarrier(cmdBuf_,
        VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
        VK_PIPELINE_STAGE_VERTEX_INPUT_BIT,
        0, 0, nullptr, 2, barriers, 0, nullptr);

    // 6. Render pass
    VkClearValue clearVal;
    clearVal.color = {{bgR_, bgG_, bgB_, 1.f}};

    VkRenderPassBeginInfo rpInfo{VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO};
    rpInfo.renderPass        = renderPass_;
    rpInfo.framebuffer       = framebuffers_[imageIndex];
    rpInfo.renderArea.offset = {0, 0};
    rpInfo.renderArea.extent = swapExtent_;
    rpInfo.clearValueCount   = 1;
    rpInfo.pClearValues      = &clearVal;

    vkCmdBeginRenderPass(cmdBuf_, &rpInfo, VK_SUBPASS_CONTENTS_INLINE);
    vkCmdBindPipeline(cmdBuf_, VK_PIPELINE_BIND_POINT_GRAPHICS, graphicsPipeline_);

    VkViewport viewport{0, 0, (float)swapExtent_.width, (float)swapExtent_.height, 0.f, 1.f};
    VkRect2D   scissor {{0, 0}, swapExtent_};
    vkCmdSetViewport(cmdBuf_, 0, 1, &viewport);
    vkCmdSetScissor(cmdBuf_, 0, 1, &scissor);

    VkBuffer     vbufs[2] = {posBuf_, colBuf_};
    VkDeviceSize offs[2]  = {0, 0};
    vkCmdBindVertexBuffers(cmdBuf_, 0, 2, vbufs, offs);
    vkCmdPushConstants(cmdBuf_, graphicsLayout_, VK_SHADER_STAGE_VERTEX_BIT,
                        0, sizeof(GraphicsPC), &gpc_);
    vkCmdDraw(cmdBuf_, (uint32_t)cpc_.numParticles, 1, 0, 0);

    vkCmdEndRenderPass(cmdBuf_);
    vkEndCommandBuffer(cmdBuf_);

    // 7. Submit
    VkPipelineStageFlags waitStage = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
    VkSubmitInfo submit{VK_STRUCTURE_TYPE_SUBMIT_INFO};
    submit.waitSemaphoreCount   = 1;
    submit.pWaitSemaphores      = &imgAvailSem_;
    submit.pWaitDstStageMask    = &waitStage;
    submit.commandBufferCount   = 1;
    submit.pCommandBuffers      = &cmdBuf_;
    submit.signalSemaphoreCount = 1;
    submit.pSignalSemaphores    = &renderDoneSem_;
    vkQueueSubmit(queue_, 1, &submit, frameFence_);

    // 8. Present
    VkPresentInfoKHR present{VK_STRUCTURE_TYPE_PRESENT_INFO_KHR};
    present.waitSemaphoreCount = 1;
    present.pWaitSemaphores    = &renderDoneSem_;
    present.swapchainCount     = 1;
    present.pSwapchains        = &swapchain_;
    present.pImageIndices      = &imageIndex;
    result = vkQueuePresentKHR(queue_, &present);
    if (result == VK_ERROR_OUT_OF_DATE_KHR || result == VK_SUBOPTIMAL_KHR) {
        recreateSwapchain((int)cpc_.width, (int)cpc_.height);
    }
}

// ── Public: touch / params ───────────────────────────────────────────────────

void ParticleFlowVK::setTouch(int idx, float x, float y) {
    if (idx < 0 || idx >= MAX_TOUCHES || !touchMapped_) return;
    float* data = (float*)touchMapped_;
    data[idx * 2]     = x;
    data[idx * 2 + 1] = y;
}

void ParticleFlowVK::clearTouch(int idx) {
    if (idx < 0 || idx >= MAX_TOUCHES || !touchMapped_) return;
    float* data = (float*)touchMapped_;
    data[idx * 2]     = -1.f;
    data[idx * 2 + 1] = -1.f;
}

void ParticleFlowVK::setParams(int numParticles, int numTouch,
                                float attract,   float drag,
                                float bgR,       float bgG,   float bgB,
                                float slowH,     float slowS, float slowV,
                                float fastH,     float fastS, float fastV,
                                int hueDir,      float pointSize) {
    cpc_.numParticles = std::max(1, std::min(numParticles, MAX_PARTICLES));
    cpc_.numTouch     = std::max(0, std::min(numTouch, MAX_TOUCHES));
    cpc_.attract      = attract;
    cpc_.drag         = drag;
    cpc_.slowH = slowH; cpc_.slowS = slowS; cpc_.slowV = slowV;
    cpc_.fastH = fastH; cpc_.fastS = fastS; cpc_.fastV = fastV;
    cpc_.hueDir       = hueDir;
    gpc_.pointSize    = pointSize;
    bgR_ = bgR; bgG_ = bgG; bgB_ = bgB;
}

// ── Public: resetParticles ───────────────────────────────────────────────────

void ParticleFlowVK::resetParticles() {
    if (!touchMapped_) return;

    // Place numTouch default attraction points in a circle
    float* td = (float*)touchMapped_;
    int N = cpc_.numTouch > 0 ? cpc_.numTouch : 1;
    float l = std::min(cpc_.width, cpc_.height) / 3.f;

    if (N == 1) {
        td[0] = cpc_.width  / 2.f;
        td[1] = cpc_.height / 2.f;
    } else {
        for (int i = 0; i < N; ++i) {
            float angle = (float)i * 2.f * (float)M_PI / (float)N;
            td[i * 2]     = cpc_.width  / 2.f + l * sinf(angle);
            td[i * 2 + 1] = cpc_.height / 2.f + l * cosf(angle);
        }
    }
    // Mark remaining slots inactive
    for (int i = N; i < MAX_TOUCHES; ++i) {
        td[i * 2]     = -1.f;
        td[i * 2 + 1] = -1.f;
    }

    dispatchInit();
}

// ── Private: Vulkan init helpers ─────────────────────────────────────────────

bool ParticleFlowVK::createInstance() {
    const char* extensions[] = {
        "VK_KHR_surface",
        "VK_KHR_android_surface",
    };
    VkApplicationInfo appInfo{VK_STRUCTURE_TYPE_APPLICATION_INFO};
    appInfo.pApplicationName   = "ParticleFlow";
    appInfo.applicationVersion = 1;
    appInfo.apiVersion         = VK_API_VERSION_1_0;

    VkInstanceCreateInfo ci{VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO};
    ci.pApplicationInfo        = &appInfo;
    ci.enabledExtensionCount   = 2;
    ci.ppEnabledExtensionNames = extensions;

    VK_CHECK(vkCreateInstance(&ci, nullptr, &instance_));
    return true;
}

bool ParticleFlowVK::selectPhysicalDevice() {
    uint32_t count = 0;
    vkEnumeratePhysicalDevices(instance_, &count, nullptr);
    if (count == 0) { LOGE("No Vulkan devices"); return false; }
    std::vector<VkPhysicalDevice> devs(count);
    vkEnumeratePhysicalDevices(instance_, &count, devs.data());
    physDev_ = devs[0];
    return true;
}

bool ParticleFlowVK::createDevice() {
    uint32_t qCount = 0;
    vkGetPhysicalDeviceQueueFamilyProperties(physDev_, &qCount, nullptr);
    std::vector<VkQueueFamilyProperties> props(qCount);
    vkGetPhysicalDeviceQueueFamilyProperties(physDev_, &qCount, props.data());

    queueFamily_ = UINT32_MAX;
    for (uint32_t i = 0; i < qCount; ++i) {
        if (props[i].queueFlags & (VK_QUEUE_GRAPHICS_BIT | VK_QUEUE_COMPUTE_BIT)) {
            queueFamily_ = i; break;
        }
    }
    if (queueFamily_ == UINT32_MAX) { LOGE("No suitable queue family"); return false; }

    float prio = 1.f;
    VkDeviceQueueCreateInfo qci{VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO};
    qci.queueFamilyIndex = queueFamily_;
    qci.queueCount       = 1;
    qci.pQueuePriorities = &prio;

    // largePoints: required for gl_PointSize > 1 in the vertex shader
    VkPhysicalDeviceFeatures features{};
    features.largePoints = VK_TRUE;

    const char* devExts[] = { "VK_KHR_swapchain" };
    VkDeviceCreateInfo dci{VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO};
    dci.queueCreateInfoCount    = 1;
    dci.pQueueCreateInfos       = &qci;
    dci.enabledExtensionCount   = 1;
    dci.ppEnabledExtensionNames = devExts;
    dci.pEnabledFeatures        = &features;

    VK_CHECK(vkCreateDevice(physDev_, &dci, nullptr, &device_));
    vkGetDeviceQueue(device_, queueFamily_, 0, &queue_);
    return true;
}

bool ParticleFlowVK::createSurface(ANativeWindow* window) {
    VkAndroidSurfaceCreateInfoKHR sci{VK_STRUCTURE_TYPE_ANDROID_SURFACE_CREATE_INFO_KHR};
    sci.window = window;
    auto fn = (PFN_vkCreateAndroidSurfaceKHR)vkGetInstanceProcAddr(instance_,
                                                                    "vkCreateAndroidSurfaceKHR");
    if (!fn) { LOGE("vkCreateAndroidSurfaceKHR not found"); return false; }
    VK_CHECK(fn(instance_, &sci, nullptr, &surface_));
    return true;
}

bool ParticleFlowVK::createSwapchain(int width, int height) {
    // Choose format
    uint32_t fmtCount = 0;
    vkGetPhysicalDeviceSurfaceFormatsKHR(physDev_, surface_, &fmtCount, nullptr);
    std::vector<VkSurfaceFormatKHR> fmts(fmtCount);
    vkGetPhysicalDeviceSurfaceFormatsKHR(physDev_, surface_, &fmtCount, fmts.data());

    swapFormat_ = fmts[0].format;
    VkColorSpaceKHR colorSpace = fmts[0].colorSpace;
    for (auto& f : fmts) {
        if (f.format == VK_FORMAT_B8G8R8A8_UNORM &&
            f.colorSpace == VK_COLOR_SPACE_SRGB_NONLINEAR_KHR) {
            swapFormat_ = f.format;
            colorSpace  = f.colorSpace;
            break;
        }
    }

    VkSurfaceCapabilitiesKHR caps;
    vkGetPhysicalDeviceSurfaceCapabilitiesKHR(physDev_, surface_, &caps);
    swapExtent_ = caps.currentExtent;
    if (swapExtent_.width == UINT32_MAX) {
        swapExtent_ = {(uint32_t)width, (uint32_t)height};
    }

    uint32_t imgCount = caps.minImageCount + 1;
    if (caps.maxImageCount > 0) imgCount = std::min(imgCount, caps.maxImageCount);

    VkSwapchainCreateInfoKHR sci{VK_STRUCTURE_TYPE_SWAPCHAIN_CREATE_INFO_KHR};
    sci.surface          = surface_;
    sci.minImageCount    = imgCount;
    sci.imageFormat      = swapFormat_;
    sci.imageColorSpace  = colorSpace;
    sci.imageExtent      = swapExtent_;
    sci.imageArrayLayers = 1;
    sci.imageUsage       = VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT;
    sci.imageSharingMode = VK_SHARING_MODE_EXCLUSIVE;
    sci.preTransform     = caps.currentTransform;
    sci.compositeAlpha   = VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR;
    sci.presentMode      = VK_PRESENT_MODE_FIFO_KHR;
    sci.clipped          = VK_TRUE;

    VK_CHECK(vkCreateSwapchainKHR(device_, &sci, nullptr, &swapchain_));

    uint32_t cnt = 0;
    vkGetSwapchainImagesKHR(device_, swapchain_, &cnt, nullptr);
    swapImages_.resize(cnt);
    vkGetSwapchainImagesKHR(device_, swapchain_, &cnt, swapImages_.data());

    swapViews_.resize(cnt);
    for (uint32_t i = 0; i < cnt; ++i) {
        VkImageViewCreateInfo ivci{VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO};
        ivci.image                           = swapImages_[i];
        ivci.viewType                        = VK_IMAGE_VIEW_TYPE_2D;
        ivci.format                          = swapFormat_;
        ivci.components                      = {VK_COMPONENT_SWIZZLE_IDENTITY,
                                                VK_COMPONENT_SWIZZLE_IDENTITY,
                                                VK_COMPONENT_SWIZZLE_IDENTITY,
                                                VK_COMPONENT_SWIZZLE_IDENTITY};
        ivci.subresourceRange.aspectMask     = VK_IMAGE_ASPECT_COLOR_BIT;
        ivci.subresourceRange.baseMipLevel   = 0;
        ivci.subresourceRange.levelCount     = 1;
        ivci.subresourceRange.baseArrayLayer = 0;
        ivci.subresourceRange.layerCount     = 1;
        VK_CHECK(vkCreateImageView(device_, &ivci, nullptr, &swapViews_[i]));
    }
    return true;
}

bool ParticleFlowVK::createRenderPass() {
    VkAttachmentDescription att{};
    att.format         = swapFormat_;
    att.samples        = VK_SAMPLE_COUNT_1_BIT;
    att.loadOp         = VK_ATTACHMENT_LOAD_OP_CLEAR;
    att.storeOp        = VK_ATTACHMENT_STORE_OP_STORE;
    att.stencilLoadOp  = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
    att.stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
    att.initialLayout  = VK_IMAGE_LAYOUT_UNDEFINED;
    att.finalLayout    = VK_IMAGE_LAYOUT_PRESENT_SRC_KHR;

    VkAttachmentReference ref{0, VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL};

    VkSubpassDescription sub{};
    sub.pipelineBindPoint    = VK_PIPELINE_BIND_POINT_GRAPHICS;
    sub.colorAttachmentCount = 1;
    sub.pColorAttachments    = &ref;

    VkSubpassDependency dep{};
    dep.srcSubpass    = VK_SUBPASS_EXTERNAL;
    dep.dstSubpass    = 0;
    dep.srcStageMask  = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
    dep.dstStageMask  = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
    dep.srcAccessMask = 0;
    dep.dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;

    VkRenderPassCreateInfo rci{VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO};
    rci.attachmentCount = 1;
    rci.pAttachments    = &att;
    rci.subpassCount    = 1;
    rci.pSubpasses      = &sub;
    rci.dependencyCount = 1;
    rci.pDependencies   = &dep;

    VK_CHECK(vkCreateRenderPass(device_, &rci, nullptr, &renderPass_));
    return true;
}

bool ParticleFlowVK::createFramebuffers() {
    framebuffers_.resize(swapViews_.size());
    for (size_t i = 0; i < swapViews_.size(); ++i) {
        VkFramebufferCreateInfo fci{VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO};
        fci.renderPass      = renderPass_;
        fci.attachmentCount = 1;
        fci.pAttachments    = &swapViews_[i];
        fci.width           = swapExtent_.width;
        fci.height          = swapExtent_.height;
        fci.layers          = 1;
        VK_CHECK(vkCreateFramebuffer(device_, &fci, nullptr, &framebuffers_[i]));
    }
    return true;
}

bool ParticleFlowVK::createBuffers() {
    VkDeviceSize posSize   = (VkDeviceSize)MAX_PARTICLES * 2 * sizeof(float);  // vec2
    VkDeviceSize velSize   = (VkDeviceSize)MAX_PARTICLES * 2 * sizeof(float);  // vec2
    VkDeviceSize colSize   = (VkDeviceSize)MAX_PARTICLES * 4 * sizeof(float);  // vec4
    VkDeviceSize touchSize = (VkDeviceSize)MAX_TOUCHES   * 2 * sizeof(float);  // vec2 per touch

    createBuffer(posSize,
        VK_BUFFER_USAGE_STORAGE_BUFFER_BIT | VK_BUFFER_USAGE_VERTEX_BUFFER_BIT,
        VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT, posBuf_, posMem_);

    createBuffer(velSize,
        VK_BUFFER_USAGE_STORAGE_BUFFER_BIT,
        VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT, velBuf_, velMem_);

    createBuffer(colSize,
        VK_BUFFER_USAGE_STORAGE_BUFFER_BIT | VK_BUFFER_USAGE_VERTEX_BUFFER_BIT,
        VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT, colBuf_, colMem_);

    createBuffer(touchSize,
        VK_BUFFER_USAGE_STORAGE_BUFFER_BIT,
        VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT,
        touchBuf_, touchMem_);

    // Persistently map touch buffer; fill with -1 sentinel
    vkMapMemory(device_, touchMem_, 0, touchSize, 0, &touchMapped_);
    float* td = (float*)touchMapped_;
    for (int i = 0; i < MAX_TOUCHES * 2; ++i) td[i] = -1.f;

    return true;
}

bool ParticleFlowVK::createDescriptors() {
    // Layout: 4 SSBOs at bindings 0-3, COMPUTE stage
    VkDescriptorSetLayoutBinding bindings[4] = {};
    for (int i = 0; i < 4; ++i) {
        bindings[i].binding         = (uint32_t)i;
        bindings[i].descriptorType  = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
        bindings[i].descriptorCount = 1;
        bindings[i].stageFlags      = VK_SHADER_STAGE_COMPUTE_BIT;
    }
    VkDescriptorSetLayoutCreateInfo lci{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO};
    lci.bindingCount = 4;
    lci.pBindings    = bindings;
    VK_CHECK(vkCreateDescriptorSetLayout(device_, &lci, nullptr, &descSetLayout_));

    // Pool
    VkDescriptorPoolSize ps{VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 4};
    VkDescriptorPoolCreateInfo pci{VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO};
    pci.flags         = VK_DESCRIPTOR_POOL_CREATE_FREE_DESCRIPTOR_SET_BIT;
    pci.maxSets       = 1;
    pci.poolSizeCount = 1;
    pci.pPoolSizes    = &ps;
    VK_CHECK(vkCreateDescriptorPool(device_, &pci, nullptr, &descPool_));

    // Allocate
    VkDescriptorSetAllocateInfo ai{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO};
    ai.descriptorPool     = descPool_;
    ai.descriptorSetCount = 1;
    ai.pSetLayouts        = &descSetLayout_;
    VK_CHECK(vkAllocateDescriptorSets(device_, &ai, &descSet_));

    // Write buffers
    VkBuffer     bufs[4]    = {posBuf_, velBuf_, colBuf_, touchBuf_};
    VkDeviceSize sizes[4]   = {
        (VkDeviceSize)MAX_PARTICLES * 2 * sizeof(float),
        (VkDeviceSize)MAX_PARTICLES * 2 * sizeof(float),
        (VkDeviceSize)MAX_PARTICLES * 4 * sizeof(float),
        (VkDeviceSize)MAX_TOUCHES   * 2 * sizeof(float),
    };

    VkWriteDescriptorSet writes[4] = {};
    VkDescriptorBufferInfo binfos[4] = {};
    for (int i = 0; i < 4; ++i) {
        binfos[i].buffer = bufs[i];
        binfos[i].offset = 0;
        binfos[i].range  = sizes[i];

        writes[i].sType           = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
        writes[i].dstSet          = descSet_;
        writes[i].dstBinding      = (uint32_t)i;
        writes[i].descriptorCount = 1;
        writes[i].descriptorType  = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
        writes[i].pBufferInfo     = &binfos[i];
    }
    vkUpdateDescriptorSets(device_, 4, writes, 0, nullptr);
    return true;
}

bool ParticleFlowVK::createComputePipelines() {
    // Shared push-constant range for both compute pipelines
    VkPushConstantRange pcr{VK_SHADER_STAGE_COMPUTE_BIT, 0, sizeof(ComputePC)};

    VkPipelineLayoutCreateInfo plci{VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO};
    plci.setLayoutCount         = 1;
    plci.pSetLayouts            = &descSetLayout_;
    plci.pushConstantRangeCount = 1;
    plci.pPushConstantRanges    = &pcr;
    VK_CHECK(vkCreatePipelineLayout(device_, &plci, nullptr, &computeLayout_));

    // Init pipeline
    VkShaderModule initMod = createShaderModule(
        reinterpret_cast<const uint32_t*>(init_comp_spv),
        init_comp_spv_len);

    VkComputePipelineCreateInfo cpci{VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO};
    cpci.stage.sType  = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    cpci.stage.stage  = VK_SHADER_STAGE_COMPUTE_BIT;
    cpci.stage.module = initMod;
    cpci.stage.pName  = "main";
    cpci.layout       = computeLayout_;
    VK_CHECK(vkCreateComputePipelines(device_, VK_NULL_HANDLE, 1, &cpci, nullptr, &initPipeline_));
    vkDestroyShaderModule(device_, initMod, nullptr);

    // Update pipeline
    VkShaderModule updateMod = createShaderModule(
        reinterpret_cast<const uint32_t*>(update_comp_spv),
        update_comp_spv_len);
    cpci.stage.module = updateMod;
    VK_CHECK(vkCreateComputePipelines(device_, VK_NULL_HANDLE, 1, &cpci, nullptr, &updatePipeline_));
    vkDestroyShaderModule(device_, updateMod, nullptr);

    return true;
}

bool ParticleFlowVK::createGraphicsPipeline() {
    VkPushConstantRange pcr{VK_SHADER_STAGE_VERTEX_BIT, 0, sizeof(GraphicsPC)};

    VkPipelineLayoutCreateInfo plci{VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO};
    plci.pushConstantRangeCount = 1;
    plci.pPushConstantRanges    = &pcr;
    VK_CHECK(vkCreatePipelineLayout(device_, &plci, nullptr, &graphicsLayout_));

    VkShaderModule vertMod = createShaderModule(
        reinterpret_cast<const uint32_t*>(particles_vert_spv),
        particles_vert_spv_len);
    VkShaderModule fragMod = createShaderModule(
        reinterpret_cast<const uint32_t*>(particles_frag_spv),
        particles_frag_spv_len);

    VkPipelineShaderStageCreateInfo stages[2] = {};
    stages[0].sType  = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    stages[0].stage  = VK_SHADER_STAGE_VERTEX_BIT;
    stages[0].module = vertMod;
    stages[0].pName  = "main";
    stages[1].sType  = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    stages[1].stage  = VK_SHADER_STAGE_FRAGMENT_BIT;
    stages[1].module = fragMod;
    stages[1].pName  = "main";

    // Vertex input: binding 0 = pos (vec2), binding 1 = col (vec4)
    VkVertexInputBindingDescription binds[2] = {};
    binds[0].binding   = 0;
    binds[0].stride    = 2 * sizeof(float);
    binds[0].inputRate = VK_VERTEX_INPUT_RATE_VERTEX;
    binds[1].binding   = 1;
    binds[1].stride    = 4 * sizeof(float);
    binds[1].inputRate = VK_VERTEX_INPUT_RATE_VERTEX;

    VkVertexInputAttributeDescription attrs[2] = {};
    attrs[0].location = 0;
    attrs[0].binding  = 0;
    attrs[0].format   = VK_FORMAT_R32G32_SFLOAT;
    attrs[0].offset   = 0;
    attrs[1].location = 1;
    attrs[1].binding  = 1;
    attrs[1].format   = VK_FORMAT_R32G32B32A32_SFLOAT;
    attrs[1].offset   = 0;

    VkPipelineVertexInputStateCreateInfo visci{VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO};
    visci.vertexBindingDescriptionCount   = 2;
    visci.pVertexBindingDescriptions      = binds;
    visci.vertexAttributeDescriptionCount = 2;
    visci.pVertexAttributeDescriptions    = attrs;

    VkPipelineInputAssemblyStateCreateInfo iasci{VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO};
    iasci.topology = VK_PRIMITIVE_TOPOLOGY_POINT_LIST;

    VkPipelineViewportStateCreateInfo vsci{VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO};
    vsci.viewportCount = 1;
    vsci.scissorCount  = 1;

    VkPipelineRasterizationStateCreateInfo rsci{VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO};
    rsci.polygonMode = VK_POLYGON_MODE_FILL;
    rsci.cullMode    = VK_CULL_MODE_NONE;
    rsci.frontFace   = VK_FRONT_FACE_COUNTER_CLOCKWISE;
    rsci.lineWidth   = 1.f;

    VkPipelineMultisampleStateCreateInfo msci{VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO};
    msci.rasterizationSamples = VK_SAMPLE_COUNT_1_BIT;

    // No blending — solid opaque; glow comes from particle density
    VkPipelineColorBlendAttachmentState cba{};
    cba.colorWriteMask = VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT |
                         VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT;
    VkPipelineColorBlendStateCreateInfo cbsci{VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO};
    cbsci.attachmentCount = 1;
    cbsci.pAttachments    = &cba;

    VkDynamicState dynStates[] = {VK_DYNAMIC_STATE_VIEWPORT, VK_DYNAMIC_STATE_SCISSOR};
    VkPipelineDynamicStateCreateInfo dsci{VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO};
    dsci.dynamicStateCount = 2;
    dsci.pDynamicStates    = dynStates;

    VkGraphicsPipelineCreateInfo gpci{VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO};
    gpci.stageCount          = 2;
    gpci.pStages             = stages;
    gpci.pVertexInputState   = &visci;
    gpci.pInputAssemblyState = &iasci;
    gpci.pViewportState      = &vsci;
    gpci.pRasterizationState = &rsci;
    gpci.pMultisampleState   = &msci;
    gpci.pColorBlendState    = &cbsci;
    gpci.pDynamicState       = &dsci;
    gpci.layout              = graphicsLayout_;
    gpci.renderPass          = renderPass_;
    gpci.subpass             = 0;

    VK_CHECK(vkCreateGraphicsPipelines(device_, VK_NULL_HANDLE, 1, &gpci, nullptr, &graphicsPipeline_));
    vkDestroyShaderModule(device_, vertMod, nullptr);
    vkDestroyShaderModule(device_, fragMod, nullptr);
    return true;
}

bool ParticleFlowVK::createCommandResources() {
    VkCommandPoolCreateInfo cpci{VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO};
    cpci.flags            = VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT;
    cpci.queueFamilyIndex = queueFamily_;
    VK_CHECK(vkCreateCommandPool(device_, &cpci, nullptr, &cmdPool_));

    VkCommandBufferAllocateInfo ai{VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO};
    ai.commandPool        = cmdPool_;
    ai.level              = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
    ai.commandBufferCount = 1;
    VK_CHECK(vkAllocateCommandBuffers(device_, &ai, &cmdBuf_));
    return true;
}

bool ParticleFlowVK::createSyncObjects() {
    VkSemaphoreCreateInfo sci{VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO};
    VK_CHECK(vkCreateSemaphore(device_, &sci, nullptr, &imgAvailSem_));
    VK_CHECK(vkCreateSemaphore(device_, &sci, nullptr, &renderDoneSem_));

    // Create fence pre-signaled so first vkWaitForFences doesn't deadlock
    VkFenceCreateInfo fci{VK_STRUCTURE_TYPE_FENCE_CREATE_INFO};
    fci.flags = VK_FENCE_CREATE_SIGNALED_BIT;
    VK_CHECK(vkCreateFence(device_, &fci, nullptr, &frameFence_));
    return true;
}

// ── Private: swapchain recreation ────────────────────────────────────────────

void ParticleFlowVK::destroySwapchain() {
    for (auto fb : framebuffers_) vkDestroyFramebuffer(device_, fb, nullptr);
    framebuffers_.clear();
    for (auto iv : swapViews_)    vkDestroyImageView(device_, iv, nullptr);
    swapViews_.clear();
    swapImages_.clear();
    if (swapchain_) { vkDestroySwapchainKHR(device_, swapchain_, nullptr); swapchain_ = VK_NULL_HANDLE; }
}

void ParticleFlowVK::recreateSwapchain(int width, int height) {
    vkDeviceWaitIdle(device_);
    destroySwapchain();
    createSwapchain(width, height);
    createFramebuffers();
    LOGI("Swapchain recreated (%dx%d)", width, height);
}

// ── Private: dispatchInit ─────────────────────────────────────────────────────

void ParticleFlowVK::dispatchInit() {
    // Wait for frame fence before touching the command buffer
    vkWaitForFences(device_, 1, &frameFence_, VK_TRUE, UINT64_MAX);

    VkCommandBufferBeginInfo bi{VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};
    bi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
    vkBeginCommandBuffer(cmdBuf_, &bi);

    // Ensure host writes to touch buffer (default attraction points) are visible
    VkMemoryBarrier hostBarrier{VK_STRUCTURE_TYPE_MEMORY_BARRIER};
    hostBarrier.srcAccessMask = VK_ACCESS_HOST_WRITE_BIT;
    hostBarrier.dstAccessMask = VK_ACCESS_SHADER_READ_BIT;
    vkCmdPipelineBarrier(cmdBuf_,
        VK_PIPELINE_STAGE_HOST_BIT,
        VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
        0, 1, &hostBarrier, 0, nullptr, 0, nullptr);

    vkCmdBindPipeline(cmdBuf_, VK_PIPELINE_BIND_POINT_COMPUTE, initPipeline_);
    vkCmdBindDescriptorSets(cmdBuf_, VK_PIPELINE_BIND_POINT_COMPUTE,
                             computeLayout_, 0, 1, &descSet_, 0, nullptr);
    cpc_.frameSeed = 0;
    vkCmdPushConstants(cmdBuf_, computeLayout_, VK_SHADER_STAGE_COMPUTE_BIT,
                        0, sizeof(ComputePC), &cpc_);
    uint32_t groups = ((uint32_t)cpc_.numParticles + 255) / 256;
    vkCmdDispatch(cmdBuf_, groups, 1, 1);

    vkEndCommandBuffer(cmdBuf_);

    VkSubmitInfo si{VK_STRUCTURE_TYPE_SUBMIT_INFO};
    si.commandBufferCount = 1;
    si.pCommandBuffers    = &cmdBuf_;
    vkQueueSubmit(queue_, 1, &si, VK_NULL_HANDLE);
    vkQueueWaitIdle(queue_);
}

// ── Private: helpers ──────────────────────────────────────────────────────────

VkShaderModule ParticleFlowVK::createShaderModule(const uint32_t* code, size_t sizeBytes) {
    VkShaderModuleCreateInfo ci{VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO};
    ci.codeSize = sizeBytes;
    ci.pCode    = code;
    VkShaderModule mod = VK_NULL_HANDLE;
    vkCreateShaderModule(device_, &ci, nullptr, &mod);
    return mod;
}

uint32_t ParticleFlowVK::findMemoryType(uint32_t filter, VkMemoryPropertyFlags props) {
    VkPhysicalDeviceMemoryProperties mp;
    vkGetPhysicalDeviceMemoryProperties(physDev_, &mp);
    for (uint32_t i = 0; i < mp.memoryTypeCount; ++i) {
        if ((filter & (1u << i)) &&
            (mp.memoryTypes[i].propertyFlags & props) == props) {
            return i;
        }
    }
    return UINT32_MAX;
}

void ParticleFlowVK::createBuffer(VkDeviceSize size, VkBufferUsageFlags usage,
                                   VkMemoryPropertyFlags props,
                                   VkBuffer& buf, VkDeviceMemory& mem) {
    VkBufferCreateInfo bci{VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO};
    bci.size        = size;
    bci.usage       = usage;
    bci.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
    vkCreateBuffer(device_, &bci, nullptr, &buf);

    VkMemoryRequirements mr;
    vkGetBufferMemoryRequirements(device_, buf, &mr);

    VkMemoryAllocateInfo ai{VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO};
    ai.allocationSize  = mr.size;
    ai.memoryTypeIndex = findMemoryType(mr.memoryTypeBits, props);
    vkAllocateMemory(device_, &ai, nullptr, &mem);
    vkBindBufferMemory(device_, buf, mem, 0);
}
